FROM golang:1.24.5-alpine AS builder

RUN apk add --no-cache git gettext ca-certificates

RUN go install github.com/cespare/reflex@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN mkdir -p tmp

EXPOSE 8080

# Ganti baris CMD yang lama menjadi ini:
CMD ["reflex", "-v", "-c", "config/reflex.conf"]